---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ include "common.names.fullname" . }}"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
  type: "ClusterIP"
  ports:
    - name: "{{ include "cosmos-validator-watcher.servicePortName" . }}"
      port: {{ .Values.service.port }}
      protocol: "TCP"
      targetPort: "{{ include "cosmos-validator-watcher.servicePortName" . }}"
...
