---
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_reviewers: 1
      enforce_admins: true
      required_status_checks:
        strict: true
        contexts: []
      restrictions: null
...
