---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "{{ include "common.names.fullname" . }}"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: "Opaque"
stringData:
  {{ include "cosmo-trigger.secretEnvPersonalAccessTokenName" . }}: {{ .Values.envSecrets.cicdPersonalAccessToken}}
  {{ include "cosmo-trigger.secretEnvTriggerTokenName" . }}: {{ .Values.envSecrets.cicdTriggerToken }}
...
