---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "{{ include "common.names.fullname" . }}"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  providers.json: |
    {{ .Values.availableChainsAndRPCEndpoints | toPrettyJson | nindent 4 }}
  wallets.json: |
    {{ .Values.wallets | nindent 4 }}
...
