{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # Allow inbound connections on the service port
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
    {{- if .Values.metrics.enabled }}
    # Allow Prometheus scrapes for metrics
    - ports:
        - port: {{ .Values.metrics.port }}
          protocol: TCP
    {{- end }}
{{- end }}
