---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "{{ include "common.names.fullname" . }}"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: "Opaque"
stringData:
  walletMnemonicMapping.json: |-
{{- .Values.walletMnemonicMapping | nindent 4 }}
...
