{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: "monitoring.coreos.com/v1"
kind: "ServiceMonitor"
metadata:
  name: "{{ include "common.names.fullname" . }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
spec:
  endpoints:
    - port: "{{ include "layer-zero.metricsPortName" . }}"
      path: "/metrics"
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
...
{{- end}}
